# Generated by Django 3.0.8 on 2020-07-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('coursenumber', models.IntegerField()),
                ('instructor', models.CharField(max_length=50)),
                ('duration', models.FloatField()),
            ],
        ),
    ]
